[OF-1494] refac: Disable warnings in csharp wrapper
Because we're not messing with the generators, disable warnings.
The specific one, (although it may just be the first) :
Error CS0109: The member 'HotspotSequenceSystem.Dispose()' does not hide an accessible member. The new keyword is not required.)